#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title: What's keeping Lizzy busy?
name: &name "Lizzy Gallagher"
email: # not going to include just yet
url: https://lizzy-gallagher.github.io

# appears in the feed.xml and the site description
description: >- # this means to ignore newlines until "baseurl:"
  This is the developer blog of Lizzy Gallager. Focusing mostly on .NET
  and API design, though I also love productivity hacks and have OPINIONS on
  front-end infrastructure, so expect those too.
twitter_username: erg.gallagher
github_username:  lizzy-gallagher
search: true

# Site author
author:
  name     : *name
  bio      : "Writing code @ Mastercard. Walking enthusiast. Not a party person."
  avatar   : "/assets/images/lizzy-author.png"
  location : "Arlington, VA"
  links:
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/Lizzy-Gallagher/"
      - label: "Twitter"
        icon: "fab fa-fw fa-twitter-square"
        url: "https://twitter.com/LizzyIsNotBusy"

twitter:
  username: "LizzyIsNotBusy"

# fixes "pages-gem" bug https://github.com/github/pages-gem/issues/399
github: [metadata]

# Build settings
markdown: kramdown

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      # read_time: true
      comments: true
      # share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

footer:
  links:
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/Lizzy-Gallagher/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/erggallagher"

# SEO Related
google_site_verification : "_vCJZHD1Olmjd5dFpiGWNubpq1r51hKObBtjsCADuiQ" # from Google Search Console
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "UA-173629504-1" # Replace this with your ID, or delete
    anonymize_ip         : true

